# If you need to add API keys (e.g. AWS Access Keys) follow the below instructions:
# https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
env:
  global:
    - AWS_DEFAULT_REGION=us-west-2 
    - AWS_ACCESS_KEY
    - AWS_SECRET_ACCESS_KEY
    - AWS_S3_BUCKET

before_install:
  - pip install --upgrade --user awscli

matrix:
  include:
    # IAM Policies
    - language: minimal
      before_install:
        - npm i
        - cd config/policies
      script:
        - npm run lint
        - make simulate

    # CloudFormation
    - language: minimal
      before_install:
        - cd config/cloudformation
      script:
        - make lint
        - make test

    # Status API
    # Status API

    # Task Scheduler
    - language: go
      before_install:
        - cd src/task-scheduler
        - go get
      script:
        - go fmt
        - go test

    # Task Scheduler API
    - language: ruby
      before_install:
        - cd src/api/internal/task-scheduler
        - gem install aws-sdk-ruby
      script:
        - make lint
        - make test

    # Model API
    - language: python
      python: 3.7
      before_install:
        - pipenv install
      script:
        - make lint
        - make test

    if: branch == master
      # Deploy CloudFormation
      # Deploy Status API
      # Deploy Task Scheduler
      # Deploy Task Scheduler API
      # Deploy Model API

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  skip_cleanup: true

notifications:
  email:
    - cole+github@colejhudson.com
