AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hidden Alphabet API

Parameters:
  AwsSqsQueueUrl:
    Type: String
    Description: AWS SQS Queue URL
  AwsRegion:
    Type: String
    Description: AWS Region where SQS Queue is located

  LambdaS3Bucket:
    Type: String
    Description: Bucket containing the lambda function zipfile
  LambdaS3Key:
    Type: String
    Description: Path to your lambda function zipfile
  LambdaS3ZipFile:
    Type: String
    Description: Name of the lambda function zipfile
  LambdaS3Role:
    Type: String
    Description: Execution role of the lambda function

Resources:
  HiddenAlphabetAPICode:
    Type: AWS::Lambda::FunctionCode
    Properties:
      S3Bucket: !Ref Parameters::LambdaS3Bucket
      S3Key: !Ref Parameters::LambdaS3Key
      ZipFile: !Ref Parameters::LambdaS3ZipFile

  HiddenAlphabetAPILambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: !Ref HiddenAlphabetAPICode
      FunctionName: hidden-alpha-api
      Handler: lambda.handler
      Runtime: ruby2.5
      Role: !Ref Parameters::LambdaS3Role
      Environment:
        Variables:
          AWS_SQS_URL: !Ref Parameters::AwsSqsQueueUrl
          AWS_REGION_CODE: !Ref Parameters::AwsRegion

Outputs:
  HiddenAlphabetScraperJobQueueAPI:
    Description: Hidden Alphabet API ARN
    Value:
      Fn::GetAtt:
      - HiddenAlphabetAPILambdaFunction
