AWSTemplateFormatVersion: 2010-09-09

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/16
      VpcId: !Ref VPC

  InternalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Internal 
      GroupDescription: Internal APIs 
      VpcId: !Ref VPC

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Public
      GroupDescription: Public APIs
      VpcId: !Ref VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  Internet:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
